### PR TITLE
Update gps code

### PR DESCRIPTION
**Pull request by Roeland54**
Added CheckGpsFix function + improve gps function.
Moved Gps related code to separate gps class.

### CODE REVIEW

**Comment by DeuxVis** [comment]
Your solution seems cleaner than what I had started to do. I'll test it ASAP. Thanks for your work.

**Comment by Roeland54** [comment]
I found a bug in the code. Will fix it asap.

**Comment by Roeland54** [comment]
So it is fixed now and tested.

**Comment by DeuxVis** [comment]
Excellent, seems to work perfectly, thanks Roeland.

**Pull request merged**
