### PR TITLE
Add support for OTAA and US915

### PR DESCRIPTION
**Pull request by fede2cr**
As define in bug #10

### CODE REVIEW

**Comment by DeuxVis** [comment]
That looks fine, thanks. I'll do a quick test before merging it.

**Comment by DeuxVis** [comment]
Just to keep you informed :
I wasn't able to have OTAA work during my quick test with your changes.
They work fine with ABP then.

I'll need to investigate more when I find some time.

**Comment by fede2cr** [comment]
Please let me know of any tests you need me to do.

I have this code running on 6 student's T-Beams in Costa Rica, with US-915MHz and OTAA.

Cheers.

**Comment by DeuxVis** [comment]
Nothing you can do at the time, thanks.
I have to setup back my gateway so I can properly test OTAA, then I'll push some minors changes and then only ask you to test them for the 915 band.

**Comment by DeuxVis** [comment]
Reminder for myself to do something about that PR.

**Comment by DeuxVis** [comment]
Thank you very much for your contribution.

As I waited too long before incorporating it, I'm going to recreate your work, with improvements, so I'm closing this PR.

See branch https://github.com/DeuxVis/Lora-TTNMapper-T-Beam/tree/OTAA_support

**Comment by DeuxVis** [comment]
Done and merged in my master. Thank you again !

**Comment by fede2cr** [comment]
Thanks a lot, will test tonight.

**Comment by DeuxVis** [comment]
You might want to wait until I also added the US915 part - that I will need help testing.

Shouldn't be long.

**Pull request closed without merging**
