### PR TITLE
Added Payload decoder to readme.md

### PR DESCRIPTION
**Pull request by Roeland54**

### CODE REVIEW

**Comment by DeuxVis** [comment]
FYI my decoder is this :

```javascript
function Decoder(bytes, port) {
    var decoded = {};

    decoded.latitude = ((bytes[0]<<16)>>>0) + ((bytes[1]<<8)>>>0) + bytes[2];
    decoded.latitude = (decoded.latitude / 16777215.0 * 180) - 90;
  
    decoded.longitude = ((bytes[3]<<16)>>>0) + ((bytes[4]<<8)>>>0) + bytes[5];
    decoded.longitude = (decoded.longitude / 16777215.0 * 360) - 180;
  
    var altValue = ((bytes[6]<<8)>>>0) + bytes[7];
    var sign = bytes[6] & (1 << 7);
    if(sign)
    {
        decoded.altitude = 0xFFFF0000 | altValue;
    }
    else
    {
        decoded.altitude = altValue;
    }
  
    decoded.hdop = bytes[8] / 10.0;

    return decoded;
}
```

The main difference is it seems to be taking care of negative altitudes.

It also does include the _hexstring_ variable in the output. Is it needed ?

**Comment by Roeland54** [comment]
Seems like your decoder is the best option. The hexstring is not needed. So maybe you can add yours instead.

**Comment by DeuxVis** [comment]
Excellent work Roeland, thanks.
Sorry not to be more responsive at the moment, I might be able to take a few minutes to test and accept your pull requests later in the week.

**Comment by Roeland54** [comment]
With pleasure. Sorry about the commit mess but I forgot that merging into my own master branch would impact this pull request. I reverted the changes.

**Pull request merged**
